# -*- mode: python ; coding: utf-8 -*-
# Auto-generated from tool_registry.py — do not edit manually.
# Regenerate: python generate_spec.py > HylToolbox.spec

from PyInstaller.utils.hooks import collect_data_files

music_datas = collect_data_files('music', includes=['weixin.png'])

a = Analysis(
    ['hyl_toolbox.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('music/ncm_to_mp3.py', 'music'),
        ('music/tab.py', 'music'),
        ('zipandpng/zipandpng.py', 'zipandpng'),
        ('zipandpng/tab.py', 'zipandpng'),
        ('mp4-mp3/converter.py', 'mp4-mp3'),
        ('mp4-mp3/tab.py', 'mp4-mp3'),
        ('mp4-mp3/config_store.py', 'mp4-mp3'),
        ('image-convert/converter.py', 'image-convert'),
        ('image-convert/tab.py', 'image-convert'),
        ('pdf-tools/converter.py', 'pdf-tools'),
        ('pdf-tools/tab.py', 'pdf-tools'),
        ('video-downloader/converter.py', 'video-downloader'),
        ('video-downloader/tab.py', 'video-downloader'),
        ('video-downloader/bin/aria2c.exe', 'video-downloader'),
        ('video-downloader/bin/aria2c.SHA256.txt', 'video-downloader'),
        ('video-downloader/models.py', 'video-downloader'),
        ('video-downloader/_shared.py', 'video-downloader'),
        ('video-downloader/source_parser.py', 'video-downloader'),
        ('video-downloader/progress.py', 'video-downloader'),
        ('video-downloader/telegram_backend.py', 'video-downloader'),
        ('video-downloader/web_backend.py', 'video-downloader'),
        ('video-downloader/tab_constants.py', 'video-downloader'),
        ('video-downloader/tab_formatters.py', 'video-downloader'),
        ('video-downloader/tab_workers.py', 'video-downloader'),
        ('video-downloader/tab_panels.py', 'video-downloader'),
        ('video-downloader/__init__.py', 'video-downloader'),
        ('name/converter.py', 'name'),
        ('name/tab.py', 'name'),
        ('分类/converter.py', '分类'),
        ('分类/tab.py', '分类'),
        ('same/converter.py', 'same'),
        ('same/tab.py', 'same'),
        ('same/_common.py', 'same'),
        ('same/exact_duplicate.py', 'same'),
        ('same/video_signature.py', 'same'),
        ('same/move_plan.py', 'same'),
        ('same/__init__.py', 'same'),
        ('base64/converter.py', 'base64'),
        ('base64/tab.py', 'base64'),
        ('themes/dark.qss', 'themes'),
        ('themes/light.qss', 'themes'),
        ('logo.png', '.'),
        ('sound.mp3', '.'),
        ('music/weixin_base64.txt', 'music'),
    ] + music_datas,
    hiddenimports=['ncmdump', 'yt_dlp', 'telethon'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='格式转换工具',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='logo.ico',
    onefile=True,
)
