# -*- mode: python ; coding: utf-8 -*-
# Auto-generated from tool_registry.py — do not edit manually.
# Regenerate: python generate_spec.py > HylToolbox.spec

from PyInstaller.utils.hooks import collect_data_files

music_datas = collect_data_files('modules.ncm-converter', includes=['weixin.png'])

a = Analysis(
    ['hyl_toolbox.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('modules/ncm-converter/ncm_to_mp3.py', 'modules/ncm-converter'),
        ('modules/ncm-converter/tab.py', 'modules/ncm-converter'),
        ('modules/file-disguise/zipandpng.py', 'modules/file-disguise'),
        ('modules/file-disguise/tab.py', 'modules/file-disguise'),
        ('modules/audio-extractor/converter.py', 'modules/audio-extractor'),
        ('modules/audio-extractor/tab.py', 'modules/audio-extractor'),
        ('modules/audio-extractor/config_store.py', 'modules/audio-extractor'),
        ('modules/image-converter/converter.py', 'modules/image-converter'),
        ('modules/image-converter/tab.py', 'modules/image-converter'),
        ('modules/pdf-tools/converter.py', 'modules/pdf-tools'),
        ('modules/pdf-tools/tab.py', 'modules/pdf-tools'),
        ('modules/video-downloader/converter.py', 'modules/video-downloader'),
        ('modules/video-downloader/tab.py', 'modules/video-downloader'),
        ('modules/video-downloader/bin/aria2c.exe', 'modules/video-downloader'),
        ('modules/video-downloader/bin/aria2c.SHA256.txt', 'modules/video-downloader'),
        ('modules/video-downloader/models.py', 'modules/video-downloader'),
        ('modules/video-downloader/_shared.py', 'modules/video-downloader'),
        ('modules/video-downloader/source_parser.py', 'modules/video-downloader'),
        ('modules/video-downloader/progress.py', 'modules/video-downloader'),
        ('modules/video-downloader/telegram_backend.py', 'modules/video-downloader'),
        ('modules/video-downloader/web_backend.py', 'modules/video-downloader'),
        ('modules/video-downloader/tab_constants.py', 'modules/video-downloader'),
        ('modules/video-downloader/tab_formatters.py', 'modules/video-downloader'),
        ('modules/video-downloader/tab_workers.py', 'modules/video-downloader'),
        ('modules/video-downloader/tab_panels.py', 'modules/video-downloader'),
        ('modules/video-downloader/__init__.py', 'modules/video-downloader'),
        ('modules/batch-rename/converter.py', 'modules/batch-rename'),
        ('modules/batch-rename/tab.py', 'modules/batch-rename'),
        ('modules/file-sorter/converter.py', 'modules/file-sorter'),
        ('modules/file-sorter/tab.py', 'modules/file-sorter'),
        ('modules/duplicate-finder/converter.py', 'modules/duplicate-finder'),
        ('modules/duplicate-finder/tab.py', 'modules/duplicate-finder'),
        ('modules/duplicate-finder/_common.py', 'modules/duplicate-finder'),
        ('modules/duplicate-finder/exact_duplicate.py', 'modules/duplicate-finder'),
        ('modules/duplicate-finder/video_signature.py', 'modules/duplicate-finder'),
        ('modules/duplicate-finder/move_plan.py', 'modules/duplicate-finder'),
        ('modules/duplicate-finder/__init__.py', 'modules/duplicate-finder'),
        ('modules/base64/converter.py', 'modules/base64'),
        ('modules/base64/tab.py', 'modules/base64'),
        ('themes/dark.qss', 'themes'),
        ('themes/light.qss', 'themes'),
        ('logo.png', '.'),
        ('sound.mp3', '.'),
        ('modules/ncm-converter/weixin_base64.txt', 'modules/ncm-converter'),
    ] + music_datas,
    hiddenimports=['ncmdump', 'yt_dlp', 'telethon'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='格式转换工具',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='logo.ico',
    onefile=True,
)
