export const uiText = {
  app: {
    title: "Hyl 工具箱",
  },
  settings: {
    browserPreview: "浏览器预览",
    wordSection: "文档",
    wordSectionTitle: "文档排版",
  },
  common: {
    runtime: "运行日志",
    detectedFiles: "识别结果",
    convertedFiles: "转换结果",
    renameResults: "重命名结果",
    previewPlan: "预览计划",
    categorySummary: "分类摘要",
    moveResults: "移动结果",
    pdfOutputs: "PDF 输出",
    wordOutputs: "排版输出",
    filesPanel: "文件列表",
    saved: "已保存",
    failed: "失败",
    hasErrors: "有错误",
    empty: "空",
    noLogs: "暂无日志",
    recentLocal: "最近 5 条本地执行记录",
    choose: "选择",
    pluginLabel: (name: string) => `插件 · ${name}`,
    charCount: (count: number) => `${count} 字`,
    pathCount: (count: number) => `${count} 个路径`,
    parsedCount: (count: number) => `已解析 ${count} 条`,
    multiLineHint: "支持多行输入",
    fileCount: (count: number) => `${count} 个文件`,
  },
  web: {
    proxyHost: "代理主机",
    proxyPort: "代理端口",
    concurrent: "并发数",
    overwrite: "覆盖同名文件",
    outputSubdirByTitle: "按标题创建子目录",
    allCandidates: "候选检查时传递全部候选",
    recentRuntime: "最近的解析、校验、候选检查或下载记录",
  },
  tg: {
    sessionPath: "会话文件路径",
    recentLimit: "最近消息数",
    allMessages: "抓取全部消息",
    includeVideos: "包含视频",
    includePhotos: "包含图片",
    dateFrom: "开始日期",
    dateTo: "结束日期",
    proxyHost: "代理主机",
    proxyPort: "代理端口",
    proxyUrl: "代理 URL",
    concurrent: "并发数",
    overwrite: "覆盖同名文件",
    outputSubdirByTitle: "按标题创建子目录",
    phoneCodeHash: "短信校验哈希",
    twoFactorPassword: "两步验证密码",
    downloadedFiles: "已下载文件",
    recentRuntime: "最近的 TG sidecar 调用记录",
  },
  wv: {
    unknownSource: "未知来源",
  },
};
